import type { Driver } from './types';

export const rookieDrivers: Driver[] = [
	{
		id: 'denis-cantero',
		name: 'Denis R. Cantero',
		number: 71,
		team: 'Mbarete Racing',
		city: 'Asunción',
		helmetColor: 'Naranja y Negro',
		photo: '/pilotos/denis-cantero.jpg',
		bio: 'Explosivo en las primeras vueltas, no le tiene miedo a nadie.',
		category: 'Rookie',
	},
	{
		id: 'francisco-candia',
		name: 'Francisco Candia',
		number: 17,
		team: 'Sin Equipo',
		city: 'Asunción',
		helmetColor: '',
		photo: '/pilotos/francisco-candia.jpg',
		bio: '',
		category: 'Rookie',
	},
	{
		id: 'francisco-rios',
		name: 'Francisco Ríos',
		number: 13,
		team: 'Hakembo',
		city: 'Luque',
		helmetColor: '',
		photo: '/pilotos/francisco-rios.jpg',
		bio: '',
		category: 'Rookie',
	},
	{
		id: 'noel-perez',
		name: 'Noel Perez',
		number: 520,
		team: 'Mad Max',
		city: 'Asunción',
		helmetColor: 'Negro, dorado, blanco',
		photo: '/pilotos/noel-perez.jpg',
		bio: 'Lo único imposible es aquello que no lo intentas.',
		category: 'Rookie',
	},
	// Extra/sin resultados aún pero misma categoría
	{
		id: 'carlos-davalos',
		name: 'Carlos Dávalos',
		number: 27,
		team: 'CDR',
		city: 'Luque',
		helmetColor: '',
		photo: '/pilotos/carlos-davalos.jpg',
		bio: '',
		category: 'Rookie',
	},
];
